### ISSUE TITLE
Sometimes there is an NRE in OnWakeUp()

### ISSUE THREAD

**Issue by cmaines** [bucketon/OWRandomSpeedrun#69]
```
NullReferenceException
Stacktrace: SpawnPoint.GetPointVelocity () (at <8585b6cb325949f692883e4747187a22>:0)
OuterWildsRandomSpeedrun.OuterWildsRandomSpeedrun.OnWakeUp () (at <2138deedeec3460aa8a3b5c9b41cfb16>:0)
GlobalMessenger.FireEvent (System.String eventType) (at <8585b6cb325949f692883e4747187a22>:0)
UnityEngine.Debug:LogException(Exception)
GlobalMessenger:FireEvent(String)
PlayerCameraEffectController:WakeUp()
PlayerCameraEffectController:OnStartOfTimeLoop(Int32)
GlobalMessenger`1:FireEvent(String, Int32)
TimeLoop:Start()
```

**Comment by bkirz** [comment]
What spawn points trigger this? Any in particular, or is this an issue across all of them?

**Comment by bucketon** [comment]
the one chris noticed it happening on was SPAWN_Observatory_Below

**Comment by bucketon** [comment]
Sorry, I was conflating this with https://github.com/bucketon/OWRandomSpeedrun/issues/68 which I now think is unrelated. I have noticed the NRE happening on subsequent loops, but not the first loop, so I think maybe because the timing is different on the second loop onward (wakeup and start of loop happen simultaneously), we might call something in a different order.

**Comment by bucketon** [comment]
https://github.com/bucketon/OWRandomSpeedrun/pull/89 fixed as a byproduct
